[build] 
  publish = "build"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.111.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.113.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.113.0" 
